### ISSUE TITLE
Run more experiments for showing success on random graph dependency on maxDistance parameter

### ISSUE THREAD

**Issue by kabirkbr** [singnet/offernet#55]
As suggested by @pennachin in face-to-face conversation, it is not clear, why in figure 3.4 of Experiment #1 documentation showing [sensitivity to graph topology](https://singnet.github.io/offernet/public/discussions/experiment-one.html#sensitivity-to-graph-topology), the success rate is lower with maxDistance = 10 than maxDistance = 5 (for random graphs). 

![image](https://user-images.githubusercontent.com/1760288/45637665-5a2ef180-baab-11e8-8079-3bf458a6c496.png)

There are three options to explain this: 1) noise; 2) bug 3) something else; The current hypothesis is that it is noise (because there is no better explanation), but in order to know for sure more experiments should be run

**Comment by kabirkbr** [comment]
after #61 the situation is this:
![image](https://user-images.githubusercontent.com/1760288/46924163-f3591580-d021-11e8-8a8d-e031dc0160b3.png)

**Comment by pennachin** [comment]
This makes a lot more sense now...
